# controllers:
#   resource:
#     path: ../src/Controller/
#     namespace: App\Controller\
#   type: attribute
# config/routes.yaml

app_homepage:
  path: /
  controller: App\Controller\TestController::index

hello:
  path: /hello/{name}
  controller: App\Controller\HelloController::hello
  defaults:
    name: "world"
